//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoDoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class appointment
    {
        public int Id { get; set; }
        public string doctor { get; set; }
        public string user { get; set; }
        public string date { get; set; }
        public string time { get; set; }
        public string astate { get; set; }
    }
}
